CXX = g++
CXXFLAGS = -std=c++17 -O2
LDLIBS = -lncurses
TARGET = sysmon
SRC = sysmon.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC) $(LDLIBS)

clean:
	rm -f $(TARGET)